export const DISPLAY_JOB_FORM = 'DISPLAY_JOB_FORM';
export const HIDE_JOB_FORM = 'HIDE_JOB_FORM';
export const DISPLAY_CONTACT_FORM = 'DISPLAY_CONTACT_FORM';
export const DISPLAY_ACTIVITY_FORM = 'DISPLAY_ACTIVITY_FORM';
export const DISPLAY_GOAL_FORM = 'DISPLAY_GOAL_FORM';
export const DISPLAY_INTERVIEW_FORM = 'DISPLAY_INTERVIEW_FORM';
export const DISPLAY_OFFER_FORM = 'DISPLAY_OFFER_FORM';
